controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true
 
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50
    
arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - shoulder_r_joint
      - bicep_r_joint
      - elbow_r_joint
      - wrist_r_joint

    constraints:
      # stopped_velocity_tolerance: 0.0
      goal_time: 0.0
    
    interface_name: position
    state_publish_rate: 25.0  # Hz
    action_monitor_rate: 10.0  # Hz